### ISSUE TITLE
Error: Uncaught (in promise) RangeError: offset is outside the bounds of the DataView

### ISSUE THREAD

**Issue by TJEEPOT** [rfvgyhn/factorio-exchange-string-parser#1]
Error appears in console when using the implementation hosted at https://fesc.pages.dev/ with the following map strings:
`>>>eNp1U89rE0EUnmkbmlZbo8SCUmoPBU8Ja6ogRbKjICKi/8I62Uzi4GYnnd2JVg/m0KPiRRC92KsVevPgrSCIgkLRk7eKFw8qFUUvQp2Z3dlM0vhgXt6+7/343pvJCABgGowAMFvAy4IGzPO5qBOP0QCArmvOuI8Dn8bE9o35DMugTWTOpM/abcJLjBPbPaErlnRFK5iEpLVSquGor+hUIxCM05B4HRLG/YgImoxjzw9oo2EjBwxCowCH9cjG9jUDUhuSU0j8moQ3SGJ/ArZltXhYtShmIRniv4Fjwm1/nnIWDu5jKqDxNSpaXk3N2dc3xKJDI5utkq6b48y/3sckF/kct23PTBRjHtOw6WFOsNdiNIqF6tytJp1VUko841KMRNAQnPoe9mnda5KVqH+CXMwJkZ0RSgpJkrEIm1FMQk/PZS1BcBzKuUqZPyE/1RGBj0Mh59IPppdxKEM6TBk0aj1bX+/1TvcJZG+QeOHxtbrbXZ0D6uzeAfO7u+pIa1vGqANgNxkOSmcqYwWfhTFnwRIWN5dqFEcTJafsnHKkHLahBifLgoT+Sn6x7Dh9sNmnTs87ZZ3sHN0D90o45YoOyqXXCebPynMuWwAE8HZx48KnWw9cmPAso9TYST2bNeO5aIwr6L/QgjFOWnUWtfy0jKRpLFukUXnUMxJwVYPw3rfna39ebVXh36c/3l+uXXXhifPF7zuVjaoEx9WuRzL1+JGSF2YUYGpuuyn00YXv3ir56sKcyigqhU5LtXlpFMDCtLTW7ko1PwsMtaopU0SwoeW3meSzMT64g3PIRZxRxeeUeq2Ubpgxg4mJ7iOIjhn0SC9E5leAzaHem/CNafvS6j9AZO9F2HMMeBbQkGuYVA3rmfoymrGR+9waN1/oCYKjylBRv6Qv+Ur/MrpU8ltAet0GVS+j/6UpQxWZIQ8P/gOkwGMx<<<` 
(from Factorio v2.0.14)

`>>>eNp1VM+L00AUnrFbNruCLNKDiq49LChCYuwqSJHMKIiI6N9gmk4l
kCZ1koC7e7CHPSqeFcReVdibBz0VBFFQWPTkbcWLB5UVRS9CfW+SabO
x++C9fPN+fPPeSwgh+8lJkgkHZcaMF7kBIUOudd6Lej0hzUiKonvOk2
lbmJG/M1mEortittwYkvtMq+HLKCwzVOMkCjFt4kmkEDF0Aqe+g4V7U
+mGftrF2qdPTjjYp3rSY4M2668vEtTRbVIfjVABbUEKKqF9xUvBl8vM
AS8KExkFZiySxA9vNN30VrPlu/GcaVv2GRvk+LSUjhQ3UxF6K81uGiR
+L/CFNJYtW8mRckU38uMklUIxG7aleG1z17Sp7LbVUHVVL/A7HULq50
EvqLko1QPlwOI52GYZGLa057IG1/iuoSUNThd4lpX8LIC12salT6sJX
JFnGXwCsuA6Bim9++3Z4M+rTYf+ffzj/dXWdUZPXax9325sOBCcxb73
jM2D+yjPmZ5Jc26xPPSR0XdvUb4yWsWKGhp+FszwSoXQhX2ABnfA1A+
PN+JomhqnHSW/9SSfNfjAynPAIs4h+SKa12iqkyVDZ/ni+T1O+VEdPT
hJgfoGKfbQnkz4Rl/7snB/qZH/X0RxjpJniU95DfN4YXtsvlTG3cA+N
2f1iT/itIIAs36BLzvlPwFFlT0XuA5knwV5eOjF6B+ka99z<<<` 
(from Factorio v0.18.47)

Full console output can be found here (errors are in order of map strings as above):
![image](https://github.com/user-attachments/assets/96b20111-423f-49ae-bae2-8e8c3115e07e)

**Comment by rfvgyhn** [comment]
Looks like two separate issues:

1. I haven't updated this to support v2.0 yet (too busy playing :)).
2. Seems like a problem with parsing `research_queue_setting`. I don't remember when that feature was added (to either the game and/or the exchange string format). I doubt I'll look into it further though so it will remain broken unless someone wants to submit a PR.

**Comment by rfvgyhn** [comment]
v2.0 strings _should_ work now as of 9291ac1. Let me know if you come across any other issues.
